//*****************************************************************************
//*****************************************************************************
//  FILENAME: PushButtonTimer.h
//   Version: 2.6, Updated on 2015/3/4 at 22:27:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PushButtonTimer_INCLUDE
#define PushButtonTimer_INCLUDE

#include <m8c.h>

#pragma fastcall16 PushButtonTimer_EnableInt
#pragma fastcall16 PushButtonTimer_DisableInt
#pragma fastcall16 PushButtonTimer_Start
#pragma fastcall16 PushButtonTimer_Stop
#pragma fastcall16 PushButtonTimer_wReadTimer                // Read  DR0
#pragma fastcall16 PushButtonTimer_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 PushButtonTimer_WritePeriod               // Write DR1
#pragma fastcall16 PushButtonTimer_wReadCompareValue         // Read  DR2
#pragma fastcall16 PushButtonTimer_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPushButtonTimer_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wPushButtonTimer_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wPushButtonTimer_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wPushButtonTimer_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wPushButtonTimer_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PushButtonTimer API.
//-------------------------------------------------

extern void PushButtonTimer_EnableInt(void);                           // Proxy 1
extern void PushButtonTimer_DisableInt(void);                          // Proxy 1
extern void PushButtonTimer_Start(void);                               // Proxy 1
extern void PushButtonTimer_Stop(void);                                // Proxy 1
extern WORD PushButtonTimer_wReadTimer(void);                          // Proxy 1
extern WORD PushButtonTimer_wReadTimerSaveCV(void);                    // Proxy 2
extern void PushButtonTimer_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD PushButtonTimer_wReadCompareValue(void);                   // Proxy 1
extern void PushButtonTimer_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPushButtonTimer_ReadCompareValue(void);       // Deprecated
extern WORD wPushButtonTimer_ReadTimerSaveCV(void);        // Deprecated
extern WORD wPushButtonTimer_ReadCounter(void);            // Obsolete
extern WORD wPushButtonTimer_ReadTimer(void);              // Deprecated
extern WORD wPushButtonTimer_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for PushButtonTimer API's.
//--------------------------------------------------

#define PushButtonTimer_CONTROL_REG_START_BIT  ( 0x01 )
#define PushButtonTimer_INT_REG_ADDR           ( 0x0e1 )
#define PushButtonTimer_INT_MASK               ( 0x02 )


//--------------------------------------------------
// Constants for PushButtonTimer user defined values
//--------------------------------------------------

#define PushButtonTimer_PERIOD                 ( 0xccd )
#define PushButtonTimer_COMPARE_VALUE          ( 0x0 )


//-------------------------------------------------
// Register Addresses for PushButtonTimer
//-------------------------------------------------

#pragma ioport  PushButtonTimer_COUNTER_LSB_REG:    0x020    //Count register LSB
BYTE            PushButtonTimer_COUNTER_LSB_REG;
#pragma ioport  PushButtonTimer_COUNTER_MSB_REG:    0x024    //Count register MSB
BYTE            PushButtonTimer_COUNTER_MSB_REG;
#pragma ioport  PushButtonTimer_PERIOD_LSB_REG: 0x021      //Period register LSB
BYTE            PushButtonTimer_PERIOD_LSB_REG;
#pragma ioport  PushButtonTimer_PERIOD_MSB_REG: 0x025      //Period register MSB
BYTE            PushButtonTimer_PERIOD_MSB_REG;
#pragma ioport  PushButtonTimer_COMPARE_LSB_REG:    0x022    //Compare register LSB
BYTE            PushButtonTimer_COMPARE_LSB_REG;
#pragma ioport  PushButtonTimer_COMPARE_MSB_REG:    0x026    //Compare register MSB
BYTE            PushButtonTimer_COMPARE_MSB_REG;
#pragma ioport  PushButtonTimer_CONTROL_LSB_REG:    0x023    //Control register LSB
BYTE            PushButtonTimer_CONTROL_LSB_REG;
#pragma ioport  PushButtonTimer_CONTROL_MSB_REG:    0x027    //Control register MSB
BYTE            PushButtonTimer_CONTROL_MSB_REG;
#pragma ioport  PushButtonTimer_FUNC_LSB_REG:   0x120      //Function register LSB
BYTE            PushButtonTimer_FUNC_LSB_REG;
#pragma ioport  PushButtonTimer_FUNC_MSB_REG:   0x124      //Function register MSB
BYTE            PushButtonTimer_FUNC_MSB_REG;
#pragma ioport  PushButtonTimer_INPUT_LSB_REG:  0x121      //Input register LSB
BYTE            PushButtonTimer_INPUT_LSB_REG;
#pragma ioport  PushButtonTimer_INPUT_MSB_REG:  0x125      //Input register MSB
BYTE            PushButtonTimer_INPUT_MSB_REG;
#pragma ioport  PushButtonTimer_OUTPUT_LSB_REG: 0x122      //Output register LSB
BYTE            PushButtonTimer_OUTPUT_LSB_REG;
#pragma ioport  PushButtonTimer_OUTPUT_MSB_REG: 0x126      //Output register MSB
BYTE            PushButtonTimer_OUTPUT_MSB_REG;
#pragma ioport  PushButtonTimer_INT_REG:       0x0e1       //Interrupt Mask Register
BYTE            PushButtonTimer_INT_REG;


//-------------------------------------------------
// PushButtonTimer Macro 'Functions'
//-------------------------------------------------

#define PushButtonTimer_Start_M \
   ( PushButtonTimer_CONTROL_LSB_REG |=  PushButtonTimer_CONTROL_REG_START_BIT )

#define PushButtonTimer_Stop_M  \
   ( PushButtonTimer_CONTROL_LSB_REG &= ~PushButtonTimer_CONTROL_REG_START_BIT )

#define PushButtonTimer_EnableInt_M   \
   M8C_EnableIntMask(  PushButtonTimer_INT_REG, PushButtonTimer_INT_MASK )

#define PushButtonTimer_DisableInt_M  \
   M8C_DisableIntMask( PushButtonTimer_INT_REG, PushButtonTimer_INT_MASK )

#endif
// end of file PushButtonTimer.h
