//*****************************************************************************
//*****************************************************************************
//  FILENAME: TenthSecondTimer.h
//   Version: 2.6, Updated on 2015/3/4 at 22:27:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef TenthSecondTimer_INCLUDE
#define TenthSecondTimer_INCLUDE

#include <m8c.h>

#pragma fastcall16 TenthSecondTimer_EnableInt
#pragma fastcall16 TenthSecondTimer_DisableInt
#pragma fastcall16 TenthSecondTimer_Start
#pragma fastcall16 TenthSecondTimer_Stop
#pragma fastcall16 TenthSecondTimer_wReadTimer                // Read  DR0
#pragma fastcall16 TenthSecondTimer_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 TenthSecondTimer_WritePeriod               // Write DR1
#pragma fastcall16 TenthSecondTimer_wReadCompareValue         // Read  DR2
#pragma fastcall16 TenthSecondTimer_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wTenthSecondTimer_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wTenthSecondTimer_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wTenthSecondTimer_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wTenthSecondTimer_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wTenthSecondTimer_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the TenthSecondTimer API.
//-------------------------------------------------

extern void TenthSecondTimer_EnableInt(void);                           // Proxy 1
extern void TenthSecondTimer_DisableInt(void);                          // Proxy 1
extern void TenthSecondTimer_Start(void);                               // Proxy 1
extern void TenthSecondTimer_Stop(void);                                // Proxy 1
extern WORD TenthSecondTimer_wReadTimer(void);                          // Proxy 1
extern WORD TenthSecondTimer_wReadTimerSaveCV(void);                    // Proxy 2
extern void TenthSecondTimer_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD TenthSecondTimer_wReadCompareValue(void);                   // Proxy 1
extern void TenthSecondTimer_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wTenthSecondTimer_ReadCompareValue(void);       // Deprecated
extern WORD wTenthSecondTimer_ReadTimerSaveCV(void);        // Deprecated
extern WORD wTenthSecondTimer_ReadCounter(void);            // Obsolete
extern WORD wTenthSecondTimer_ReadTimer(void);              // Deprecated
extern WORD wTenthSecondTimer_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for TenthSecondTimer API's.
//--------------------------------------------------

#define TenthSecondTimer_CONTROL_REG_START_BIT ( 0x01 )
#define TenthSecondTimer_INT_REG_ADDR          ( 0x0e1 )
#define TenthSecondTimer_INT_MASK              ( 0x02 )


//--------------------------------------------------
// Constants for TenthSecondTimer user defined values
//--------------------------------------------------

#define TenthSecondTimer_PERIOD                ( 0xccd )
#define TenthSecondTimer_COMPARE_VALUE         ( 0x0 )


//-------------------------------------------------
// Register Addresses for TenthSecondTimer
//-------------------------------------------------

#pragma ioport  TenthSecondTimer_COUNTER_LSB_REG:   0x020    //Count register LSB
BYTE            TenthSecondTimer_COUNTER_LSB_REG;
#pragma ioport  TenthSecondTimer_COUNTER_MSB_REG:   0x024    //Count register MSB
BYTE            TenthSecondTimer_COUNTER_MSB_REG;
#pragma ioport  TenthSecondTimer_PERIOD_LSB_REG:    0x021     //Period register LSB
BYTE            TenthSecondTimer_PERIOD_LSB_REG;
#pragma ioport  TenthSecondTimer_PERIOD_MSB_REG:    0x025     //Period register MSB
BYTE            TenthSecondTimer_PERIOD_MSB_REG;
#pragma ioport  TenthSecondTimer_COMPARE_LSB_REG:   0x022    //Compare register LSB
BYTE            TenthSecondTimer_COMPARE_LSB_REG;
#pragma ioport  TenthSecondTimer_COMPARE_MSB_REG:   0x026    //Compare register MSB
BYTE            TenthSecondTimer_COMPARE_MSB_REG;
#pragma ioport  TenthSecondTimer_CONTROL_LSB_REG:   0x023    //Control register LSB
BYTE            TenthSecondTimer_CONTROL_LSB_REG;
#pragma ioport  TenthSecondTimer_CONTROL_MSB_REG:   0x027    //Control register MSB
BYTE            TenthSecondTimer_CONTROL_MSB_REG;
#pragma ioport  TenthSecondTimer_FUNC_LSB_REG:  0x120      //Function register LSB
BYTE            TenthSecondTimer_FUNC_LSB_REG;
#pragma ioport  TenthSecondTimer_FUNC_MSB_REG:  0x124      //Function register MSB
BYTE            TenthSecondTimer_FUNC_MSB_REG;
#pragma ioport  TenthSecondTimer_INPUT_LSB_REG: 0x121      //Input register LSB
BYTE            TenthSecondTimer_INPUT_LSB_REG;
#pragma ioport  TenthSecondTimer_INPUT_MSB_REG: 0x125      //Input register MSB
BYTE            TenthSecondTimer_INPUT_MSB_REG;
#pragma ioport  TenthSecondTimer_OUTPUT_LSB_REG:    0x122     //Output register LSB
BYTE            TenthSecondTimer_OUTPUT_LSB_REG;
#pragma ioport  TenthSecondTimer_OUTPUT_MSB_REG:    0x126     //Output register MSB
BYTE            TenthSecondTimer_OUTPUT_MSB_REG;
#pragma ioport  TenthSecondTimer_INT_REG:       0x0e1      //Interrupt Mask Register
BYTE            TenthSecondTimer_INT_REG;


//-------------------------------------------------
// TenthSecondTimer Macro 'Functions'
//-------------------------------------------------

#define TenthSecondTimer_Start_M \
   ( TenthSecondTimer_CONTROL_LSB_REG |=  TenthSecondTimer_CONTROL_REG_START_BIT )

#define TenthSecondTimer_Stop_M  \
   ( TenthSecondTimer_CONTROL_LSB_REG &= ~TenthSecondTimer_CONTROL_REG_START_BIT )

#define TenthSecondTimer_EnableInt_M   \
   M8C_EnableIntMask(  TenthSecondTimer_INT_REG, TenthSecondTimer_INT_MASK )

#define TenthSecondTimer_DisableInt_M  \
   M8C_DisableIntMask( TenthSecondTimer_INT_REG, TenthSecondTimer_INT_MASK )

#endif
// end of file TenthSecondTimer.h
