PROJNAME=Project1
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/Users/russe/OneDrive/College/2018_F~1/ESE566~1/ESE566~1/Project1/Project1
PSOCDIR=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CYPRES~1
INCLUDE_PATH=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CYPRES~1/tools/include/CY8C29~1
CSRCS=
LIBCSRCS=
STDCSRCS=
ASMSRCS= isrs.asm main.asm
LIBASMSRCS= dualadc_1.asm dualadc_1int.asm lcd.asm lpf2_1.asm lpf2_2.asm pga_1.asm pga_2.asm pga_3.asm pga_4.asm psocconfig.asm psocconfigtbl.asm psocgpioint.asm pushbuttontimer.asm pushbuttontimerint.asm stopwatchtimer.asm stopwatchtimerint.asm
STDASMSRCS=
OBJECT_SOURCES= isrs.asm main.asm
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=project1 
